name: aya
description: A Planet Journal.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/sun.png
    - assets/images/moon.png
    - assets/images/mercury.png
    - assets/images/venus.png
    - assets/images/earth.png
    - assets/images/mars.png
    - assets/images/jupiter.png
    - assets/images/saturn.png
    - assets/images/uranus.png
    - assets/images/neptune.png
    - assets/images/diameter.png
    - assets/images/planetType.png

  fonts:
    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
